### ISSUE TITLE
Cannot erase STM32F401

### ISSUE THREAD

**Issue by myst729** [KarlK90/tinyuf2-unlocker#1]
I follow the guide and successfully build an `erase.uf2` for stm32f401 (changing every line of `f411` to `f401` in your repo). No errors, everything seems fine.

Double tap reset, drag the uf2 file into blackpill mass storage, it ejects. Then I flash my own f401 bin file with QMK Toolbox (the firmware works as expected before I try tinyuf2), the log say it's done 100% by STM32 DFU. After a reboot, it's still blackpill (adafruit tinyuf2 0.10.2 flashed via QMK Toolbox the other day). Also tried with STM32Cube with no luck.

**Comment by myst729** [comment]
For some reason I couldn't erase the chip with my CMSIS-DAP: https://github.com/adafruit/tinyuf2/pull/189#issuecomment-1236127524. Could you release a uf2 file for STM32F401? Thanks.

**Comment by KarlK90** [comment]
I'm currently not at home so can't help you right now. But if you want to flash another QMK keyboard why not stick to tinyuf2 as the bootloader type?

**Comment by myst729** [comment]
It's a general purpose board, not only for QMK. I frequently flash with various firmwares, either by myself or from other interesting projects. Sometimes I randomly use QMK Toolbox because it's a handy GUI over command line.

I'm not in a hurry. It would be appreciated when you have time to lend a hand. Thanks.

**Comment by myst729** [comment]
Hello, any updates?😀

**Comment by myst729** [comment]
Well, I finally bought an ST-Link.
